# Generated by Django 3.1.6 on 2021-03-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming_assignments', '0002_auto_20210330_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='extended_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
