# Generated by Django 3.1.6 on 2021-03-20 07:30

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210319_1945'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programming_assignments', '0002_auto_20210319_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('duration', models.DurationField()),
                ('late_duration', models.DurationField()),
                ('allowed_ip_range', models.CharField(max_length=100)),
                ('assignment',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='programming_assignments.assignment')),
                ('course',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='ExamHistory',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('ip_address',
                 django.contrib.postgres.fields.ArrayField(
                     base_field=models.CharField(max_length=100),
                     blank=True,
                     null=True,
                     size=None)),
                ('is_paused', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField()),
                ('remaining_time', models.DurationField()),
                ('additional_time',
                 django.contrib.postgres.fields.ArrayField(
                     base_field=models.FloatField(),
                     blank=True,
                     null=True,
                     size=None)),
                ('exam',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='programming_assignments.exam')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
