# Generated by Django 3.1.6 on 2021-03-30 04:42

from django.db import migrations, models
import programming_assignments.models


class Migration(migrations.Migration):

    dependencies = [
        ('programming_assignments', '0003_auto_20210330_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleprogrammingassignmenthistory',
            name='file_submitted',
            field=models.FileField(blank=True, null=True, upload_to=programming_assignments.models.programming_assignment_file_upload_path),
        ),
    ]
