# Generated by Django 3.1.6 on 2021-03-30 04:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import programming_assignments.models


class Migration(migrations.Migration):

    dependencies = [
        ('programming_assignments', '0004_auto_20210330_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleprogrammingassignment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=programming_assignments.models.programming_assignment_file_upload_path),
        ),
        migrations.AlterField(
            model_name='simpleprogrammingassignmenthistory',
            name='file_submitted',
            field=models.FileField(default=datetime.datetime(2021, 3, 30, 4, 43, 44, 975452, tzinfo=utc), upload_to=programming_assignments.models.programming_assignment_file_upload_path),
            preserve_default=False,
        ),
    ]
