# Generated by Django 3.1.6 on 2021-03-28 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cribs', '0002_auto_20210319_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crib',
            name='modified_on',
        ),
        migrations.AddField(
            model_name='crib',
            name='status',
            field=models.CharField(choices=[('R', 'Resolved'), ('U', 'Unresolved')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='crib',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crib',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crib_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
