version: '3.4'

services:
  backend:
    image: bodhitree:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8765"]
    volumes:
      - .:/bodhitree  # bind mount for hot reloading of changes during debugging
    ports:
      - 8765:8765 # for vs code debugger
      - 5678:5678 # for debugpy
      - 8764:8764 # just exposing if we want to run manage.py runserver 0.0.0.0:8764 inside container without vs code debugging
