version: '3.4'

services:
  backend:
    # Use surrajk/bodhitree or ghcr.io/suraj-iitb/bodhitree
    # Use latest or v*.*.*
    image: ghcr.io/suraj-iitb/bodhitree:latest
    ports:
      - 8765:8765
      - 8764:8764 # For directly running `manage.py runserver 0.0.0.0:8764` inside container (sometime required)
    deploy:
      replicas: ${BODHITREE_REPLICAS:-1}
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        window: 60s