version: '3.4'

services:
  backend:
    image: ${BDODHITREE_IMAGE}:${BDODHITREE_TAG}
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py test
    restart: always

  db:
    restart: always