version: '3.4'

services:
  backend:
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:13.2
    volumes:
      - bodhitree_postgres_volume:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
    bodhitree_postgres_volume:
