version: '3.4'

services:
  backend:
    networks:
      - bodhitree_network
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13.2
    volumes:
      - bodhitree_postgres_volume:/var/lib/postgresql/data
    networks:
      - bodhitree_network
    env_file:
      - ./.env

volumes:
  bodhitree_postgres_volume:

networks:
  bodhitree_network:
