[tool.isort]
known_third_party = [
    "django"
]
combine_as_imports = true
force_grid_wrap = false
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true
lines_after_imports = 2

[tool.black]
line-length = 88
