# Generated by Django 3.2 on 2021-05-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='unique_schedule',
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('course', 'start_date', 'end_date', 'content_list'), name='unique_schedule'),
        ),
    ]
