# Generated by Django 3.1.6 on 2021-05-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('O', 'Open'), ('M', 'Moderated')], default='M', max_length=1),
        ),
    ]
