# Generated by Django 3.1.6 on 2021-03-11 12:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='coursehistory',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='coursehistory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField(blank=True)),
                ('content_sequence', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
