# Generated by Django 3.1.6 on 2021-04-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210404_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursehistory',
            options={'ordering': ['-id']},
        ),
    ]
