# Generated by Django 3.1.6 on 2021-03-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(),
        ),
    ]
