# Generated by Django 3.1.6 on 2021-03-20 06:34

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import subjective_assignments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programming_assignments', '0002_auto_20210319_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectiveAssignment',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('team_size', models.IntegerField()),
                ('question_file',
                 models.FileField(upload_to=subjective_assignments.models.
                                  assignment_file_upload_path)),
                ('helper_file',
                 models.FileField(upload_to=subjective_assignments.models.
                                  assignment_file_upload_path)),
                ('files_to_be_submitted',
                 django.contrib.postgres.fields.ArrayField(
                     base_field=models.IntegerField(),
                     blank=True,
                     null=True,
                     size=None)),
                ('assignment',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='programming_assignments.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectiveAssignmentTeam',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('subjective_assignment',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='subjective_assignments.subjectiveassignment')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectiveAssignmentHistory',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('marks_obtained', models.FloatField()),
                ('assignment_history',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='programming_assignments.assignmenthistory')),
                ('subjective_assignment_team',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='subjective_assignments.subjectiveassignmentteam')),
                ('submitted_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
