# Generated by Django 3.2 on 2021-05-15 04:06

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import subjective_assignments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectiveAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('extended_date', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('team_size', models.IntegerField(default=1)),
                ('question_file', models.FileField(upload_to=subjective_assignments.models.subjective_assignment_file_upload_path)),
                ('helper_file', models.FileField(blank=True, null=True, upload_to=subjective_assignments.models.subjective_assignment_file_upload_path)),
                ('files_to_be_submitted', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectiveAssignmentTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('subjective_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjective_assignments.subjectiveassignment')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectiveAssignmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_feedback', models.TextField(blank=True)),
                ('submitted_file', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=subjective_assignments.models.subjective_assignment_file_upload_path), blank=True, null=True, size=None)),
                ('marks_obtained', models.FloatField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjective_assignments.subjectiveassignment')),
                ('subjective_assignment_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjective_assignments.subjectiveassignmentteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
