# Generated by Django 3.2 on 2021-05-17 18:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAnswerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.TextField()),
                ('answer_description', models.TextField()),
                ('hint', models.TextField(blank=True)),
                ('max_no_of_attempts', models.IntegerField()),
                ('marks', models.IntegerField(default=0)),
                ('gradable', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('answer', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleCorrectQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.TextField()),
                ('answer_description', models.TextField()),
                ('hint', models.TextField(blank=True)),
                ('max_no_of_attempts', models.IntegerField()),
                ('marks', models.IntegerField(default=0)),
                ('gradable', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('correct_options', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('questions_sequence', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SingleCorrectQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.TextField()),
                ('answer_description', models.TextField()),
                ('hint', models.TextField(blank=True)),
                ('max_no_of_attempts', models.IntegerField()),
                ('marks', models.IntegerField(default=0)),
                ('gradable', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('correct_option', models.IntegerField()),
                ('question_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questionmodule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SingleCorrectQuestionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_times_attempted', models.IntegerField(default=0)),
                ('marks_obtained', models.IntegerField(default=0)),
                ('hint_taken', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('option_selected', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.singlecorrectquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('question_module_sequence', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.chapter')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.section')),
            ],
        ),
        migrations.AddField(
            model_name='questionmodule',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.CreateModel(
            name='MultipleCorrectQuestionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_times_attempted', models.IntegerField(default=0)),
                ('marks_obtained', models.IntegerField(default=0)),
                ('hint_taken', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('options_selected', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.multiplecorrectquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='multiplecorrectquestion',
            name='question_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questionmodule'),
        ),
        migrations.CreateModel(
            name='FixedAnswerQuestionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_times_attempted', models.IntegerField(default=0)),
                ('marks_obtained', models.IntegerField(default=0)),
                ('hint_taken', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('answer_submitted', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.fixedanswerquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fixedanswerquestion',
            name='question_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questionmodule'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(check=models.Q(('chapter__isnull', False), ('section__isnull', False), _connector='OR'), name='both_not_null_in_quiz'),
        ),
    ]
