# Generated by Django 3.1.6 on 2021-03-15 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('author_category',
                 models.CharField(choices=[('I', 'Instructor'),
                                           ('T', 'Teaching Assistant'),
                                           ('S', 'Student')],
                                  default='S',
                                  max_length=1)),
                ('content', models.TextField()),
                ('pinned', models.BooleanField(default=False)),
                ('anonymous_to_student', models.BooleanField(default=False)),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionComment',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('content',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='discussion_forum.content')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionForum',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('anonymous_to_instructor', models.BooleanField(default=False)),
                ('send_email_to_all', models.BooleanField(default=False)),
                ('course',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionThread',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('mark_as_important', models.BooleanField(default=False)),
                ('content',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='discussion_forum.content')),
                ('discussion_forum',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='discussion_forum.discussionforum')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('tag_name', models.TextField()),
                ('content',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='discussion_forum.content')),
                ('discussion_forum',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='discussion_forum.discussionforum')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionThreadTag',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('discussion_thread',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='discussion_forum.discussionthread')),
                ('tag',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='discussion_forum.tag')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionReply',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('content',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='discussion_forum.content')),
                ('discussion_comment',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='discussion_forum.discussioncomment')),
            ],
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='discussion_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='discussion_forum.discussionthread'),
        ),
    ]
