# Generated by Django 3.1.6 on 2021-04-12 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210411_1754'),
        ('discussion_forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionforum',
            name='anonymous_to_instructor',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='discussionforum',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='df_settings', to='course.course'),
        ),
        migrations.AlterField(
            model_name='discussionforum',
            name='send_email_to_all',
            field=models.BooleanField(),
        ),
    ]
