# Generated by Django 3.1.6 on 2021-03-19 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('discussion_forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='content',
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='tag',
            field=models.ManyToManyField(to='discussion_forum.Tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='content_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='content_type',
            field=models.CharField(choices=[('V', 'Video'), ('D', 'Document'),
                                            ('Q', 'Quiz'), ('S', 'Section')],
                                   default='D',
                                   max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussioncomment',
            name='content',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to='discussion_forum.content'),
        ),
        migrations.AlterField(
            model_name='discussionforum',
            name='course',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to='course.course'),
        ),
        migrations.AlterField(
            model_name='discussionreply',
            name='content',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to='discussion_forum.content'),
        ),
        migrations.AlterField(
            model_name='discussionthread',
            name='content',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to='discussion_forum.content'),
        ),
        migrations.DeleteModel(name='DiscussionThreadTag',),
    ]
