# Generated by Django 3.2 on 2021-05-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussioncomment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='discussionreply',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='discussionthread',
            options={'ordering': ['-id']},
        ),
    ]
