# Generated by Django 3.1.6 on 2021-03-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forum', '0002_auto_20210328_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionthread',
            name='tag',
            field=models.ManyToManyField(blank=True, to='discussion_forum.Tag'),
        ),
    ]
