# Generated by Django 3.1.6 on 2021-04-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forum', '0002_auto_20210412_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionforum',
            name='anonymous_to_instructor',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='discussionforum',
            name='send_email_to_all',
            field=models.BooleanField(default=False),
        ),
    ]
