# Generated by Django 3.2 on 2021-05-13 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='registration.college'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
