# Generated by Django 3.1.6 on 2021-03-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.plantype'),
        ),
    ]
