# Generated by Django 3.2 on 2021-05-13 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210513_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.college'),
        ),
    ]
