# Generated by Django 3.1.6 on 2021-03-13 12:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('time', models.DurationField()),
                ('marker_type',
                 models.CharField(choices=[('S', 'Section marker'),
                                           ('Q', 'Quiz marker')],
                                  default='Q',
                                  max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField(blank=True)),
                ('video_file',
                 models.FileField(upload_to=video.models.video_upload_path)),
                ('doc_file',
                 models.FileField(
                     blank=True,
                     null=True,
                     upload_to=video.models.video_doc_upload_path)),
                ('invideo_quiz_file',
                 models.FileField(
                     blank=True,
                     null=True,
                     upload_to=video.models.in_video_quiz_upload_path)),
                ('video_duration', models.DurationField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('chapter',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='course.chapter')),
                ('section',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='course.section')),
            ],
        ),
        migrations.CreateModel(
            name='VideoHistory',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('video_watched_duration',
                 models.DurationField(default=datetime.timedelta(0))),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
                ('video',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='video.video')),
            ],
        ),
        migrations.CreateModel(
            name='SectionMarker',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('marker',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='video.marker')),
            ],
        ),
        migrations.CreateModel(
            name='QuizMarker',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('quiz', models.IntegerField()),
                ('marker',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='video.marker')),
            ],
        ),
        migrations.AddField(
            model_name='marker',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='video.video'),
        ),
    ]
