# Generated by Django 3.1.6 on 2021-03-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20210330_0925'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='video',
            name='both_not_null',
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.CheckConstraint(check=models.Q(('chapter__isnull', False), ('section__isnull', False), _connector='OR'), name='both_not_null_in_video'),
        ),
    ]
