# Generated by Django 3.1.6 on 2021-03-15 05:45

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email_list',
                 django.contrib.postgres.fields.ArrayField(
                     base_field=models.EmailField(max_length=254), size=None)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('cc_list',
                 django.contrib.postgres.fields.ArrayField(
                     base_field=models.EmailField(max_length=254),
                     blank=True,
                     size=None)),
                ('subject', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('course',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='course.course')),
                ('sender',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
