# Generated by Django 3.2 on 2021-05-12 16:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='cc_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None),
        ),
    ]
