# Generated by Django 3.2 on 2021-05-13 06:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_notices', '0002_alter_email_cc_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='cc_list',
            new_name='cc',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='to_email_list',
            new_name='to',
        ),
        migrations.AddField(
            model_name='email',
            name='bcc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None),
        ),
    ]
